"""make price nullable

Revision ID: 5e7252df4663
Revises: 40dddc5d931d
Create Date: 2026-08-29 02:26:57.943005

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e7252df4663"
down_revision: Union[str, Sequence[str], None] = "40dddc5d931d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


op.alter_column("items", "price", nullable=True)
