"""add owner_id to items

Revision ID: 6b95e4e39daf
Revises: dc4b61069655
Create Date: 2026-08-26 20:23:40.920530

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b95e4e39daf"
down_revision: Union[str, Sequence[str], None] = "dc4b61069655"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("heartbeats")
    op.add_column("items", sa.Column("price", sa.Float(), nullable=False))
    op.add_column("items", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "items", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "items", type_="foreignkey")
    op.drop_column("items", "owner_id")
    op.drop_column("items", "price")
    op.create_table(
        "heartbeats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("heartbeats_pkey")),
    )
    # ### end Alembic commands ###
