"""add hashed_password to users

Revision ID: dc4b61069655
Revises: 72d5ef84c1a4
Create Date: 2026-08-18 11:46:51.361676

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dc4b61069655"
down_revision: Union[str, Sequence[str], None] = "72d5ef84c1a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("heartbeats")
    op.create_unique_constraint(None, "items", ["title"])
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    op.drop_constraint(None, "items", type_="unique")
    op.create_table(
        "heartbeats",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("heartbeats_pkey")),
    )
    # ### end Alembic commands ###
